// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Procura.API.Shared.Data;

#nullable disable

namespace Procura.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260926042200_AddApprovalWorkflowManagement")]
    partial class AddApprovalWorkflowManagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Procura.API.AI.Entities.WorkflowInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuditTrailJson")
                        .HasColumnType("text");

                    b.Property<string>("ContextJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentStage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("EstimatedTotal")
                        .HasColumnType("numeric");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlanJson")
                        .HasColumnType("text");

                    b.Property<Guid?>("ProcurementRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequestNumber")
                        .HasColumnType("text");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequesterRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProcurementRequestId");

                    b.HasIndex("RequesterId");

                    b.ToTable("WorkflowInstances");
                });

            modelBuilder.Entity("Procura.API.Modules.ApprovalWorkflow.Entities.AIAgentExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ApprovalWorkflowId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExecutionOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ExecutionStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("InputSummary")
                        .HasColumnType("text");

                    b.Property<string>("OutputSummary")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ToolExecutionMetadata")
                        .HasColumnType("text");

                    b.Property<string>("ValidationResult")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalWorkflowId");

                    b.ToTable("AIAgentExecutions");
                });

            modelBuilder.Entity("Procura.API.Modules.ApprovalWorkflow.Entities.ApprovalDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApprovalWorkflowId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ManagerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalWorkflowId");

                    b.HasIndex("ManagerId");

                    b.ToTable("ApprovalDecisions");
                });

            modelBuilder.Entity("Procura.API.Modules.ApprovalWorkflow.Entities.ApprovalWorkflow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProcurementRequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProcurementRequestId")
                        .IsUnique();

                    b.ToTable("ApprovalWorkflows");
                });

            modelBuilder.Entity("Procura.API.Modules.ApprovalWorkflow.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApprovalWorkflowId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RecipientUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalWorkflowId");

                    b.HasIndex("IsRead");

                    b.HasIndex("RecipientUserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Procura.API.Modules.ProcurementRequest.Entities.ProcurementRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("EstimatedTotal")
                        .HasColumnType("numeric");

                    b.Property<string>("Justification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RequiredByDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RequestNumber")
                        .IsUnique();

                    b.HasIndex("RequesterId");

                    b.ToTable("ProcurementRequests");
                });

            modelBuilder.Entity("Procura.API.Modules.ProcurementRequest.Entities.ProcurementRequestItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("EstimatedUnitPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("ProcurementRequestId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("ProcurementRequestId");

                    b.ToTable("ProcurementRequestItems");
                });

            modelBuilder.Entity("Procura.API.Modules.VendorEvaluation.Entities.VendorEvaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("GeneratedByAgent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<decimal>("OverallScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("ProcurementRequestId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<string>("Reasoning")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RiskFlags")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProcurementRequestId");

                    b.HasIndex("VendorId");

                    b.HasIndex("ProcurementRequestId", "VendorId");

                    b.ToTable("VendorEvaluations");
                });

            modelBuilder.Entity("Procura.API.Modules.VendorEvaluation.Entities.VendorEvaluationCriterionScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CriterionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("VendorEvaluationId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Weight")
                        .HasPrecision(4, 3)
                        .HasColumnType("decimal(4,3)");

                    b.HasKey("Id");

                    b.HasIndex("VendorEvaluationId");

                    b.ToTable("VendorEvaluationCriterionScores");
                });

            modelBuilder.Entity("Procura.API.Modules.VendorEvaluation.Entities.VendorQuote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EstimatedDeliveryDays")
                        .HasColumnType("integer");

                    b.Property<bool>("IsComplianceApproved")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("ProcurementRequestId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("QuotedPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ReliabilityRating")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid");

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("VendorQuotes");
                });

            modelBuilder.Entity("Procura.API.Modules.VendorManagement.Entities.Vendor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("numeric");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("Procura.API.Modules.VendorManagement.Entities.VendorSelection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProcurementRequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProcurementRequestId");

                    b.HasIndex("VendorId");

                    b.ToTable("VendorSelections");
                });

            modelBuilder.Entity("Procura.API.Shared.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Procura.API.Modules.ApprovalWorkflow.Entities.AIAgentExecution", b =>
                {
                    b.HasOne("Procura.API.Modules.ApprovalWorkflow.Entities.ApprovalWorkflow", "ApprovalWorkflow")
                        .WithMany("AIAgentExecutions")
                        .HasForeignKey("ApprovalWorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovalWorkflow");
                });

            modelBuilder.Entity("Procura.API.Modules.ApprovalWorkflow.Entities.ApprovalDecision", b =>
                {
                    b.HasOne("Procura.API.Modules.ApprovalWorkflow.Entities.ApprovalWorkflow", "ApprovalWorkflow")
                        .WithMany("Decisions")
                        .HasForeignKey("ApprovalWorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Procura.API.Shared.Entities.User", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovalWorkflow");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("Procura.API.Modules.ApprovalWorkflow.Entities.ApprovalWorkflow", b =>
                {
                    b.HasOne("Procura.API.Modules.ProcurementRequest.Entities.ProcurementRequest", "ProcurementRequest")
                        .WithOne("ApprovalWorkflow")
                        .HasForeignKey("Procura.API.Modules.ApprovalWorkflow.Entities.ApprovalWorkflow", "ProcurementRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcurementRequest");
                });

            modelBuilder.Entity("Procura.API.Modules.ApprovalWorkflow.Entities.Notification", b =>
                {
                    b.HasOne("Procura.API.Modules.ApprovalWorkflow.Entities.ApprovalWorkflow", "ApprovalWorkflow")
                        .WithMany("Notifications")
                        .HasForeignKey("ApprovalWorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Procura.API.Shared.Entities.User", "RecipientUser")
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovalWorkflow");

                    b.Navigation("RecipientUser");
                });

            modelBuilder.Entity("Procura.API.Modules.ProcurementRequest.Entities.ProcurementRequest", b =>
                {
                    b.HasOne("Procura.API.Shared.Entities.User", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("Procura.API.Modules.ProcurementRequest.Entities.ProcurementRequestItem", b =>
                {
                    b.HasOne("Procura.API.Modules.ProcurementRequest.Entities.ProcurementRequest", "ProcurementRequest")
                        .WithMany("Items")
                        .HasForeignKey("ProcurementRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcurementRequest");
                });

            modelBuilder.Entity("Procura.API.Modules.VendorEvaluation.Entities.VendorEvaluationCriterionScore", b =>
                {
                    b.HasOne("Procura.API.Modules.VendorEvaluation.Entities.VendorEvaluation", "VendorEvaluation")
                        .WithMany("CriterionScores")
                        .HasForeignKey("VendorEvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VendorEvaluation");
                });

            modelBuilder.Entity("Procura.API.Modules.ApprovalWorkflow.Entities.ApprovalWorkflow", b =>
                {
                    b.Navigation("AIAgentExecutions");

                    b.Navigation("Decisions");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Procura.API.Modules.ProcurementRequest.Entities.ProcurementRequest", b =>
                {
                    b.Navigation("ApprovalWorkflow");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("Procura.API.Modules.VendorEvaluation.Entities.VendorEvaluation", b =>
                {
                    b.Navigation("CriterionScores");
                });
#pragma warning restore 612, 618
        }
    }
}
