using System;

namespace Procura.API.Modules.ApprovalWorkflow.Entities
{
    /// <summary>
    /// Represents an auditable record of an AI agent execution within the workflow lifecycle.
    /// Captures inputs, outputs, validation outcomes, and tool execution metadata without
    /// storing unconstrained chain-of-thought data.
    /// </summary>
    public class AIAgentExecution
    {
        public Guid Id { get; set; } = Guid.NewGuid();

        /// <summary>
        /// Foreign key to the parent ApprovalWorkflow.
        /// </summary>
        public Guid ApprovalWorkflowId { get; set; }

        /// <summary>
        /// Navigation property to the parent ApprovalWorkflow.
        /// </summary>
        public ApprovalWorkflow ApprovalWorkflow { get; set; } = null!;

        /// <summary>
        /// Name of the executing AI agent (e.g., "ProcurementDecisionSupportAgent").
        /// </summary>
        public string AgentName { get; set; } = string.Empty;

        /// <summary>
        /// Ordinal sequence of this execution within the workflow.
        /// </summary>
        public int ExecutionOrder { get; set; }

        /// <summary>
        /// Execution status (e.g., "COMPLETED", "FAILED", "NEEDS_USER_INPUT").
        /// </summary>
        public string ExecutionStatus { get; set; } = string.Empty;

        /// <summary>
        /// Sanitized summary of input data provided to the agent.
        /// </summary>
        public string? InputSummary { get; set; }

        /// <summary>
        /// Structured summary of output or recommendations generated by the agent.
        /// </summary>
        public string? OutputSummary { get; set; }

        /// <summary>
        /// Deterministic validation result (e.g., "PASSED", "FAILED: Missing justification").
        /// </summary>
        public string? ValidationResult { get; set; }

        /// <summary>
        /// JSON metadata recording allow-listed tools invoked during execution.
        /// </summary>
        public string? ToolExecutionMetadata { get; set; }

        /// <summary>
        /// Timestamp when agent execution commenced.
        /// </summary>
        public DateTime StartedAt { get; set; } = DateTime.UtcNow;

        /// <summary>
        /// Timestamp when agent execution finished.
        /// </summary>
        public DateTime? CompletedAt { get; set; }
    }
}
