using System;
using Procura.API.Modules.ApprovalWorkflow.Enums;
using Procura.API.Shared.Entities;

namespace Procura.API.Modules.ApprovalWorkflow.Entities
{
    /// <summary>
    /// Represents an auditable notification generated by workflow lifecycle transitions
    /// and assigned to a specific recipient user.
    /// </summary>
    public class Notification
    {
        public Guid Id { get; set; } = Guid.NewGuid();

        /// <summary>
        /// Foreign key to the related ApprovalWorkflow.
        /// </summary>
        public Guid ApprovalWorkflowId { get; set; }

        /// <summary>
        /// Navigation property to the parent ApprovalWorkflow.
        /// </summary>
        public ApprovalWorkflow ApprovalWorkflow { get; set; } = null!;

        /// <summary>
        /// Foreign key identifying the intended recipient (User).
        /// </summary>
        public Guid RecipientUserId { get; set; }

        /// <summary>
        /// Navigation property to the recipient User entity.
        /// </summary>
        public User RecipientUser { get; set; } = null!;

        /// <summary>
        /// Subject or concise title of the notification.
        /// </summary>
        public string Title { get; set; } = string.Empty;

        /// <summary>
        /// Detailed body message of the notification.
        /// </summary>
        public string Message { get; set; } = string.Empty;

        /// <summary>
        /// Workflow event type that triggered this notification.
        /// </summary>
        public NotificationType Type { get; set; }

        /// <summary>
        /// Indicates whether the recipient has acknowledged/read the notification.
        /// </summary>
        public bool IsRead { get; set; } = false;

        /// <summary>
        /// Timestamp when the notification was generated.
        /// </summary>
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    }
}
